### ISSUE TITLE
Starting bot error

### ISSUE THREAD

**Issue by torin-stephen** [NedAckland/DogeBot#2]
I'm probably doing this wrong, but I get this error when running "node app.js"

![image](https://user-images.githubusercontent.com/30649929/113606317-c0ff6080-963f-11eb-90f0-a6cf3ab72efb.png)

I have installed all dependencies, and haven't edited the files cloned.

**Comment by NedAckland** [comment]
have you setup the bot token?

**Comment by torin-stephen** [comment]
I have setup bot token, and are using room id from regular dogehouse.

**Comment by torin-stephen** [comment]
I am using windows 10.

I tried to run with base code, the example on the npmjs page, still an error in the dogehouse.js package.

![image](https://user-images.githubusercontent.com/30649929/113701698-63ffbb00-96d0-11eb-99bc-a486659d278b.png)

**Comment by NedAckland** [comment]
I do. Doodle#3531

**Comment by torin-stephen** [comment]
Reinstalled node. I had it updated but something was wrong. It is fixed now.  Thanks for all help.
